test('Our first test', () => {
    throw new Error('Something failed');
});